import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1756512503293 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`insert into cenario_atual(descricao) values ('Dificuldade na compreensão dos conceitos do Scrum'), ('Aumentar'), ('Dificuldade de trabalhar em equipe'), ('Falta de motivação'), ('Dificuldade no gerenciamento de tempo'), ('Dificuldade em priorizar tarefas'), ('Dificuldade em aprender novas ferramentas'), ('Falta de habilidades de comunicação'), ('Dificuldade de equilibrar estudo com outras responsabilidades'), ('Dificuldade em gerenciar ansiedade'), ('Dificuldade em lidar com ferramentas de desenvolvimento'), ('Dificuldade de encontrar oportunidades de estágio'), ('Dificuldade em lidar com pressão'), ('Dificuldade de trabalhar com prazos apertados')`);
        await queryRunner.query(`insert into cenario_desejado (descricao) values ('Criar um ambiente de aprendizagem motivador e envolvente'), ('Aumentar a motivação e concentração dos alunos'), ('Desenvolver habilidades cognitivas, sociais e de aprendizagem'), ('Estimular a criatividade e a inovação'), ('Aumentar a retenção de conhecimentos adquiridos'), ('Promover a participação ativa dos alunos'), ('Melhorar a colaboração e o trabalho em equipe'), ('Incentivar a aplicação prática dos conhecimentos')`);
        await queryRunner.query(`insert into agrupamento_scrum(descricao) values ('Papéis'), ('Eventos'), ('Artefatos')`);
        await queryRunner.query(`insert into scrum (descricao, "idAgScrumId") values ('Scrum Master', (select id from agrupamento_scrum where descricao = 'Papéis')), ('Product Owner', (select id from agrupamento_scrum where descricao = 'Papéis')), ('Development Team', (select id from agrupamento_scrum where descricao = 'Papéis')), ('Sprint', (select id from agrupamento_scrum where descricao = 'Eventos')), ('Sprint Planning', (select id from agrupamento_scrum where descricao = 'Eventos')), ('Daily Scrum', (select id from agrupamento_scrum where descricao = 'Eventos')), ('Sprint Review', (select id from agrupamento_scrum where descricao = 'Eventos')), ('Sprint Retrospective', (select id from agrupamento_scrum where descricao = 'Eventos')), ('Product Backlog', (select id from agrupamento_scrum where descricao = 'Artefatos')), ('Sprint Backlog', (select id from agrupamento_scrum where descricao = 'Artefatos'))`);
        await queryRunner.query(`insert into perfil_jogador (descricao) values ('Jogador Competitivo'), ('Jogador Cooperativo'), ('Jogador Imersivo'), ('Jogador de Realização'), ('Jogador Social')`);
        await queryRunner.query(`insert into agrupamento_gamificacao  (descricao) values ('Desempenho'), ('Ecológico'), ('Social'), ('Pessoal'), ('Ficcional')`);
        await queryRunner.query(`insert into gamificacao  (descricao, "agGamificacaoId") values ('Pontuação',(select id from agrupamento_gamificacao where descricao = 'Desempenho')), ('Progressão',(select id from agrupamento_gamificacao where descricao = 'Desempenho')), ('Nível',(select id from agrupamento_gamificacao where descricao = 'Desempenho')),('Estatística',(select id from agrupamento_gamificacao where descricao = 'Desempenho')),('Reconhecimento',(select id from agrupamento_gamificacao where descricao = 'Desempenho'))`);
        await queryRunner.query(`insert into gamificacao  (descricao, "agGamificacaoId") values ('Chance',(select id from agrupamento_gamificacao where descricao = 'Ecológico')), ('Escolha Imposta',(select id from agrupamento_gamificacao where descricao = 'Ecológico')), ('Economia',(select id from agrupamento_gamificacao where descricao = 'Ecológico')),('Raridade',(select id from agrupamento_gamificacao where descricao = 'Ecológico')),('Pressão Temporal',(select id from agrupamento_gamificacao where descricao = 'Ecológico'))`);
        await queryRunner.query(`insert into gamificacao  (descricao, "agGamificacaoId") values ('Competição',(select id from agrupamento_gamificacao where descricao = 'Social')), ('Cooperação',(select id from agrupamento_gamificacao where descricao = 'Social')), ('Reputação',(select id from agrupamento_gamificacao where descricao = 'Social')),('Pressão Social',(select id from agrupamento_gamificacao where descricao = 'Social'))`);
        await queryRunner.query(`insert into gamificacao  (descricao, "agGamificacaoId") values ('Sensação',(select id from agrupamento_gamificacao where descricao = 'Pessoal')), ('Objetivo',(select id from agrupamento_gamificacao where descricao = 'Pessoal')), ('Quebra-cabeça',(select id from agrupamento_gamificacao where descricao = 'Pessoal')),('Novidade',(select id from agrupamento_gamificacao where descricao = 'Pessoal')),('Renovação',(select id from agrupamento_gamificacao where descricao = 'Pessoal'))`);
        await queryRunner.query(`insert into gamificacao  (descricao, "agGamificacaoId") values ('Narrativa',(select id from agrupamento_gamificacao where descricao = 'Ficcional')), ('Storytelling',(select id from agrupamento_gamificacao where descricao = 'Ficcional'))`);
        await queryRunner.query(`insert into agrupamento_mapeamento (descricao ) values ('Modalidade'), ('Tipos'), ('Geral')`);
        await queryRunner.query(`insert into mapeamento  (descricao, "agMapeamentoId") values ('Presencial',(select id from agrupamento_mapeamento where descricao = 'Modalidade')), ('Online',(select id from agrupamento_mapeamento where descricao = 'Modalidade')), ('Individual',(select id from agrupamento_mapeamento where descricao = 'Modalidade')), ('Em grupo',(select id from agrupamento_mapeamento where descricao = 'Modalidade')), ('Uso de plataformas online',(select id from agrupamento_mapeamento where descricao = 'Modalidade'))`);
        await queryRunner.query(`insert into mapeamento  (descricao, "agMapeamentoId") values ('Formativa',(select id from agrupamento_mapeamento where descricao = 'Tipos')), ('Somativa',(select id from agrupamento_mapeamento where descricao = 'Tipos'))`);
        await queryRunner.query(`insert into mapeamento  (descricao, "agMapeamentoId") values ('Requer equipamentos específicos',(select id from agrupamento_mapeamento where descricao = 'Geral')), ('Foco em projetos reais',(select id from agrupamento_mapeamento where descricao = 'Geral')), ('Níveis de dificuldades progressivos',(select id from agrupamento_mapeamento where descricao = 'Geral'))`);
        await queryRunner.query(`insert into agrupamento_recompensa (descricao) values ('Recompensas Internas'), ('Recompensas Externas')`);
        await queryRunner.query(`insert into recompensa  (descricao, "agRecompensaId") values ('Pontos',(select id from agrupamento_recompensa where descricao = 'Recompensas Internas')), ('Distintivos',(select id from agrupamento_recompensa where descricao = 'Recompensas Internas')), ('Acesso à recursos exclusivos',(select id from agrupamento_recompensa where descricao = 'Recompensas Internas')), ('Vantagens em desafios',(select id from agrupamento_recompensa where descricao = 'Recompensas Internas')), ('Reconhecimento',(select id from agrupamento_recompensa where descricao = 'Recompensas Internas'))`);
        await queryRunner.query(`insert into recompensa  (descricao, "agRecompensaId") values ('Certificados Digitais',(select id from agrupamento_recompensa where descricao = 'Recompensas Externas')), ('Brindes',(select id from agrupamento_recompensa where descricao = 'Recompensas Externas')), ('Oportunidades para liderar a turma',(select id from agrupamento_recompensa where descricao = 'Recompensas Externas')), ('Participação em eventos ou viagens',(select id from agrupamento_recompensa where descricao = 'Recompensas Externas')), ('Reconhecimento Público',(select id from agrupamento_recompensa where descricao = 'Recompensas Externas')), ('Prêmios em dinheiro ou descontos',(select id from agrupamento_recompensa where descricao = 'Recompensas Externas'))`);
        await queryRunner.query(`insert into acao_recompensada  (descricao) values ('Participação ativa durante as atividades'), ('Conclusão de tarefas dentro do prazo'), ('Atingir pontuação elevada nas atividades'), ('Colaboração com outros alunos ou equipes'), ('Contribuição em atividades'), ('Demonstrar pensamento crítico em tarefas desafiadoras'), ('Auxiliar colegas com dificuldades'), ('Apresentar um trabalho com excelência'), ('Atender prontamente as solicitações do professor'), ('Realizar atividades extra em casa')`);
        await queryRunner.query(`insert into regra (descricao) values ('Respeite as regras do jogo e as decisões do professor em todas as atividades'), ('Seja respeitoso e colaborativo com outros jogadores em todas as atividades'), ('Entenda as regras do jogo e como elas se aplicam a cada atividade'), ('Busque sempre aprender e se esforçar para alcançar seus objetivos em cada atividade'), ('Comunique-se com outros jogadores de forma clara e objetiva em todas as atividades'), ('Proteja a privacidade e a segurança de todos os jogadores em todas as atividades'), ('Use dispositivos eletrônicos apenas para fins educacionais relacionados ao jogo'), ('Respeite as regras e políticas da instituição em todas as atividades'), ('Mantenha-se atualizado com as atualizações nas regras do jogo em todas as atividades'), ('Busque sempre a supervisão do professor em todas as atividades')`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
