import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1757170662447 implements MigrationInterface {
    name = 'Default1757170662447'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "agrupamento_scrum" ("id" SERIAL NOT NULL, "descricao" character varying(50) NOT NULL, CONSTRAINT "PK_0679c467dd59f7665c1a9599e4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scrum" ("id" SERIAL NOT NULL, "descricao" character varying(50) NOT NULL, "ativo" boolean NOT NULL DEFAULT false, "idAgScrumId" integer, CONSTRAINT "PK_da2735230f879eae58c628a9385" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "regra" ("id" SERIAL NOT NULL, "descricao" text NOT NULL, "ativo" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_980f173a0f9be0cfa23d8ddbe93" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "perfil_jogador" ("id" SERIAL NOT NULL, "descricao" character varying(50) NOT NULL, "ativo" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_b68d2e97134c1d740c579c360a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cenario_atual" ("id" SERIAL NOT NULL, "descricao" character varying(100) NOT NULL, "ativo" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_693c4f33e39ae6eea9bc804e196" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cenario_desejado" ("id" SERIAL NOT NULL, "descricao" character varying(100) NOT NULL, "ativo" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_80acc1db7bd8716c1521a083fc7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "acao_recompensada" ("id" SERIAL NOT NULL, "descricao" character varying(250) NOT NULL, "ativo" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_da5885cb64a74142c01b44e0999" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "agrupamento_recompensa" ("id" SERIAL NOT NULL, "descricao" character varying(50) NOT NULL, CONSTRAINT "PK_b3cd27a9d0d9607778fa3b59a15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recompensa" ("id" SERIAL NOT NULL, "descricao" character varying(50) NOT NULL, "ativo" boolean NOT NULL DEFAULT false, "agRecompensaId" integer, CONSTRAINT "PK_537296c431e11f8315250ca1d9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "agrupamento_gamificacao" ("id" SERIAL NOT NULL, "descricao" character varying(50) NOT NULL, CONSTRAINT "PK_90625010726b1a989c456d72440" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gamificacao" ("id" SERIAL NOT NULL, "descricao" character varying(50) NOT NULL, "ativo" boolean NOT NULL DEFAULT false, "agGamificacaoId" integer, CONSTRAINT "PK_ca7b32eb568343904948587e62b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "agrupamento_mapeamento" ("id" SERIAL NOT NULL, "descricao" character varying(50) NOT NULL, CONSTRAINT "PK_e3cf6a3f317f56e7f8e0bfd57aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mapeamento" ("id" SERIAL NOT NULL, "descricao" character varying(50) NOT NULL, "ativo" boolean NOT NULL DEFAULT false, "agMapeamentoId" integer, CONSTRAINT "PK_7118817ba5f63d155fa4569fcaf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "planejamento" ("id" SERIAL NOT NULL, "descricao" character varying(50), "ativo" boolean DEFAULT false, "turmaId" integer, CONSTRAINT "PK_5ce4e86c1d5595697e4d542cf22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "turma" ("id" SERIAL NOT NULL, "nome_professor" character varying(50) NOT NULL, "email_professor" character varying(50) NOT NULL, "nome_instituicao" character varying(50) NOT NULL, "nome_disciplina" character varying(50) NOT NULL, "identificacao_turma" character varying(50) NOT NULL, "tipo_atividade" character varying(50) NOT NULL, "qtd_participantes" integer NOT NULL, "duracao_prevista" integer NOT NULL, "localizacao_atividade" character varying(50) NOT NULL, CONSTRAINT "PK_b7da8685b4c588d7bb0c3b30930" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sugestao" ("id" SERIAL NOT NULL, "origem_tipo" character varying(250) NOT NULL, "origem_id" integer NOT NULL, "destino_tipo" character varying NOT NULL, "destino_id" character varying(250) NOT NULL, "ativo" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_e2db8738b5a8ae3c62bb7f09cc5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "planejamento_scrums_scrum" ("planejamentoId" integer NOT NULL, "scrumId" integer NOT NULL, CONSTRAINT "PK_eacc5fe001695ef8c05464733fe" PRIMARY KEY ("planejamentoId", "scrumId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_afdcd96d8818bd43fad8c4c06f" ON "planejamento_scrums_scrum" ("planejamentoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_39cff654c9e94491744c778587" ON "planejamento_scrums_scrum" ("scrumId") `);
        await queryRunner.query(`CREATE TABLE "planejamento_regras_regra" ("planejamentoId" integer NOT NULL, "regraId" integer NOT NULL, CONSTRAINT "PK_df188f128026f3597cb8243339b" PRIMARY KEY ("planejamentoId", "regraId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5265f6bcdf5b87ada1dec5b799" ON "planejamento_regras_regra" ("planejamentoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ba1ca6373cf4a240461125a4e" ON "planejamento_regras_regra" ("regraId") `);
        await queryRunner.query(`CREATE TABLE "planejamento_recompensas_recompensa" ("planejamentoId" integer NOT NULL, "recompensaId" integer NOT NULL, CONSTRAINT "PK_1241ab7b05d719b53d70a6475fe" PRIMARY KEY ("planejamentoId", "recompensaId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a059397ee94b3ef1cfe211a57b" ON "planejamento_recompensas_recompensa" ("planejamentoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_49a910f747d3ed5adb2cb4a1d7" ON "planejamento_recompensas_recompensa" ("recompensaId") `);
        await queryRunner.query(`CREATE TABLE "planejamento_elementos_gamificacao_gamificacao" ("planejamentoId" integer NOT NULL, "gamificacaoId" integer NOT NULL, CONSTRAINT "PK_d6f8643c0b6d8e15c4b9aaa405b" PRIMARY KEY ("planejamentoId", "gamificacaoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_48bdd63b173fe20acd39339515" ON "planejamento_elementos_gamificacao_gamificacao" ("planejamentoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_413ebc17b7810865da85150c8c" ON "planejamento_elementos_gamificacao_gamificacao" ("gamificacaoId") `);
        await queryRunner.query(`CREATE TABLE "planejamento_perfis_jogador_perfil_jogador" ("planejamentoId" integer NOT NULL, "perfilJogadorId" integer NOT NULL, CONSTRAINT "PK_dfc9ba5a9a459d830cbfb32db80" PRIMARY KEY ("planejamentoId", "perfilJogadorId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a3ce94d21846141a2ed0e2b244" ON "planejamento_perfis_jogador_perfil_jogador" ("planejamentoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_65b52807e2334fbdf963dc813b" ON "planejamento_perfis_jogador_perfil_jogador" ("perfilJogadorId") `);
        await queryRunner.query(`CREATE TABLE "planejamento_cenarios_atuais_cenario_atual" ("planejamentoId" integer NOT NULL, "cenarioAtualId" integer NOT NULL, CONSTRAINT "PK_5d68fc18b54cc425705d1d7706e" PRIMARY KEY ("planejamentoId", "cenarioAtualId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_75c6c4ffc37f4534e3b150fc67" ON "planejamento_cenarios_atuais_cenario_atual" ("planejamentoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b1bee37e78136e4f29f530217" ON "planejamento_cenarios_atuais_cenario_atual" ("cenarioAtualId") `);
        await queryRunner.query(`CREATE TABLE "planejamento_cenarios_desejados_cenario_desejado" ("planejamentoId" integer NOT NULL, "cenarioDesejadoId" integer NOT NULL, CONSTRAINT "PK_ca9cf1b94a51bef575ca555383d" PRIMARY KEY ("planejamentoId", "cenarioDesejadoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ddebf42279fd5516083aa440a3" ON "planejamento_cenarios_desejados_cenario_desejado" ("planejamentoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad92e6a57b4ee729847118895e" ON "planejamento_cenarios_desejados_cenario_desejado" ("cenarioDesejadoId") `);
        await queryRunner.query(`CREATE TABLE "planejamento_acoes_recompensadas_acao_recompensada" ("planejamentoId" integer NOT NULL, "acaoRecompensadaId" integer NOT NULL, CONSTRAINT "PK_8a723080e223822c3b16675b35c" PRIMARY KEY ("planejamentoId", "acaoRecompensadaId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_434e59e1f1a8dd9b26401ab6af" ON "planejamento_acoes_recompensadas_acao_recompensada" ("planejamentoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_00f2718fe189f00ae21442ea9c" ON "planejamento_acoes_recompensadas_acao_recompensada" ("acaoRecompensadaId") `);
        await queryRunner.query(`CREATE TABLE "planejamento_mapeamentos_mapeamento" ("planejamentoId" integer NOT NULL, "mapeamentoId" integer NOT NULL, CONSTRAINT "PK_b00cf1373ac1db34c82d3a319a2" PRIMARY KEY ("planejamentoId", "mapeamentoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9f957366a2d97bcea1115ba1b4" ON "planejamento_mapeamentos_mapeamento" ("planejamentoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bba22ddc41a621e5d20cfdc7c7" ON "planejamento_mapeamentos_mapeamento" ("mapeamentoId") `);
        await queryRunner.query(`ALTER TABLE "scrum" ADD CONSTRAINT "FK_795c66612a67540edf87b974254" FOREIGN KEY ("idAgScrumId") REFERENCES "agrupamento_scrum"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recompensa" ADD CONSTRAINT "FK_9214664af5c82c2182e3031ea55" FOREIGN KEY ("agRecompensaId") REFERENCES "agrupamento_recompensa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gamificacao" ADD CONSTRAINT "FK_41648ac35c314964d2425c59d4e" FOREIGN KEY ("agGamificacaoId") REFERENCES "agrupamento_gamificacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mapeamento" ADD CONSTRAINT "FK_035fe9d7bea798ab9efce33bdd2" FOREIGN KEY ("agMapeamentoId") REFERENCES "agrupamento_mapeamento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planejamento" ADD CONSTRAINT "FK_1612ff3c88c9de8d9d698919b19" FOREIGN KEY ("turmaId") REFERENCES "turma"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planejamento_scrums_scrum" ADD CONSTRAINT "FK_afdcd96d8818bd43fad8c4c06f1" FOREIGN KEY ("planejamentoId") REFERENCES "planejamento"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_scrums_scrum" ADD CONSTRAINT "FK_39cff654c9e94491744c7785879" FOREIGN KEY ("scrumId") REFERENCES "scrum"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_regras_regra" ADD CONSTRAINT "FK_5265f6bcdf5b87ada1dec5b7992" FOREIGN KEY ("planejamentoId") REFERENCES "planejamento"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_regras_regra" ADD CONSTRAINT "FK_3ba1ca6373cf4a240461125a4e9" FOREIGN KEY ("regraId") REFERENCES "regra"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_recompensas_recompensa" ADD CONSTRAINT "FK_a059397ee94b3ef1cfe211a57b6" FOREIGN KEY ("planejamentoId") REFERENCES "planejamento"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_recompensas_recompensa" ADD CONSTRAINT "FK_49a910f747d3ed5adb2cb4a1d7a" FOREIGN KEY ("recompensaId") REFERENCES "recompensa"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_elementos_gamificacao_gamificacao" ADD CONSTRAINT "FK_48bdd63b173fe20acd393395159" FOREIGN KEY ("planejamentoId") REFERENCES "planejamento"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_elementos_gamificacao_gamificacao" ADD CONSTRAINT "FK_413ebc17b7810865da85150c8ca" FOREIGN KEY ("gamificacaoId") REFERENCES "gamificacao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_perfis_jogador_perfil_jogador" ADD CONSTRAINT "FK_a3ce94d21846141a2ed0e2b2442" FOREIGN KEY ("planejamentoId") REFERENCES "planejamento"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_perfis_jogador_perfil_jogador" ADD CONSTRAINT "FK_65b52807e2334fbdf963dc813b3" FOREIGN KEY ("perfilJogadorId") REFERENCES "perfil_jogador"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_cenarios_atuais_cenario_atual" ADD CONSTRAINT "FK_75c6c4ffc37f4534e3b150fc671" FOREIGN KEY ("planejamentoId") REFERENCES "planejamento"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_cenarios_atuais_cenario_atual" ADD CONSTRAINT "FK_3b1bee37e78136e4f29f530217d" FOREIGN KEY ("cenarioAtualId") REFERENCES "cenario_atual"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planejamento_cenarios_desejados_cenario_desejado" ADD CONSTRAINT "FK_ddebf42279fd5516083aa440a39" FOREIGN KEY ("planejamentoId") REFERENCES "planejamento"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_cenarios_desejados_cenario_desejado" ADD CONSTRAINT "FK_ad92e6a57b4ee729847118895e1" FOREIGN KEY ("cenarioDesejadoId") REFERENCES "cenario_desejado"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_acoes_recompensadas_acao_recompensada" ADD CONSTRAINT "FK_434e59e1f1a8dd9b26401ab6af0" FOREIGN KEY ("planejamentoId") REFERENCES "planejamento"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_acoes_recompensadas_acao_recompensada" ADD CONSTRAINT "FK_00f2718fe189f00ae21442ea9cc" FOREIGN KEY ("acaoRecompensadaId") REFERENCES "acao_recompensada"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_mapeamentos_mapeamento" ADD CONSTRAINT "FK_9f957366a2d97bcea1115ba1b48" FOREIGN KEY ("planejamentoId") REFERENCES "planejamento"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planejamento_mapeamentos_mapeamento" ADD CONSTRAINT "FK_bba22ddc41a621e5d20cfdc7c79" FOREIGN KEY ("mapeamentoId") REFERENCES "mapeamento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "planejamento_mapeamentos_mapeamento" DROP CONSTRAINT "FK_bba22ddc41a621e5d20cfdc7c79"`);
        await queryRunner.query(`ALTER TABLE "planejamento_mapeamentos_mapeamento" DROP CONSTRAINT "FK_9f957366a2d97bcea1115ba1b48"`);
        await queryRunner.query(`ALTER TABLE "planejamento_acoes_recompensadas_acao_recompensada" DROP CONSTRAINT "FK_00f2718fe189f00ae21442ea9cc"`);
        await queryRunner.query(`ALTER TABLE "planejamento_acoes_recompensadas_acao_recompensada" DROP CONSTRAINT "FK_434e59e1f1a8dd9b26401ab6af0"`);
        await queryRunner.query(`ALTER TABLE "planejamento_cenarios_desejados_cenario_desejado" DROP CONSTRAINT "FK_ad92e6a57b4ee729847118895e1"`);
        await queryRunner.query(`ALTER TABLE "planejamento_cenarios_desejados_cenario_desejado" DROP CONSTRAINT "FK_ddebf42279fd5516083aa440a39"`);
        await queryRunner.query(`ALTER TABLE "planejamento_cenarios_atuais_cenario_atual" DROP CONSTRAINT "FK_3b1bee37e78136e4f29f530217d"`);
        await queryRunner.query(`ALTER TABLE "planejamento_cenarios_atuais_cenario_atual" DROP CONSTRAINT "FK_75c6c4ffc37f4534e3b150fc671"`);
        await queryRunner.query(`ALTER TABLE "planejamento_perfis_jogador_perfil_jogador" DROP CONSTRAINT "FK_65b52807e2334fbdf963dc813b3"`);
        await queryRunner.query(`ALTER TABLE "planejamento_perfis_jogador_perfil_jogador" DROP CONSTRAINT "FK_a3ce94d21846141a2ed0e2b2442"`);
        await queryRunner.query(`ALTER TABLE "planejamento_elementos_gamificacao_gamificacao" DROP CONSTRAINT "FK_413ebc17b7810865da85150c8ca"`);
        await queryRunner.query(`ALTER TABLE "planejamento_elementos_gamificacao_gamificacao" DROP CONSTRAINT "FK_48bdd63b173fe20acd393395159"`);
        await queryRunner.query(`ALTER TABLE "planejamento_recompensas_recompensa" DROP CONSTRAINT "FK_49a910f747d3ed5adb2cb4a1d7a"`);
        await queryRunner.query(`ALTER TABLE "planejamento_recompensas_recompensa" DROP CONSTRAINT "FK_a059397ee94b3ef1cfe211a57b6"`);
        await queryRunner.query(`ALTER TABLE "planejamento_regras_regra" DROP CONSTRAINT "FK_3ba1ca6373cf4a240461125a4e9"`);
        await queryRunner.query(`ALTER TABLE "planejamento_regras_regra" DROP CONSTRAINT "FK_5265f6bcdf5b87ada1dec5b7992"`);
        await queryRunner.query(`ALTER TABLE "planejamento_scrums_scrum" DROP CONSTRAINT "FK_39cff654c9e94491744c7785879"`);
        await queryRunner.query(`ALTER TABLE "planejamento_scrums_scrum" DROP CONSTRAINT "FK_afdcd96d8818bd43fad8c4c06f1"`);
        await queryRunner.query(`ALTER TABLE "planejamento" DROP CONSTRAINT "FK_1612ff3c88c9de8d9d698919b19"`);
        await queryRunner.query(`ALTER TABLE "mapeamento" DROP CONSTRAINT "FK_035fe9d7bea798ab9efce33bdd2"`);
        await queryRunner.query(`ALTER TABLE "gamificacao" DROP CONSTRAINT "FK_41648ac35c314964d2425c59d4e"`);
        await queryRunner.query(`ALTER TABLE "recompensa" DROP CONSTRAINT "FK_9214664af5c82c2182e3031ea55"`);
        await queryRunner.query(`ALTER TABLE "scrum" DROP CONSTRAINT "FK_795c66612a67540edf87b974254"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bba22ddc41a621e5d20cfdc7c7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f957366a2d97bcea1115ba1b4"`);
        await queryRunner.query(`DROP TABLE "planejamento_mapeamentos_mapeamento"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00f2718fe189f00ae21442ea9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_434e59e1f1a8dd9b26401ab6af"`);
        await queryRunner.query(`DROP TABLE "planejamento_acoes_recompensadas_acao_recompensada"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad92e6a57b4ee729847118895e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddebf42279fd5516083aa440a3"`);
        await queryRunner.query(`DROP TABLE "planejamento_cenarios_desejados_cenario_desejado"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b1bee37e78136e4f29f530217"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75c6c4ffc37f4534e3b150fc67"`);
        await queryRunner.query(`DROP TABLE "planejamento_cenarios_atuais_cenario_atual"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65b52807e2334fbdf963dc813b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3ce94d21846141a2ed0e2b244"`);
        await queryRunner.query(`DROP TABLE "planejamento_perfis_jogador_perfil_jogador"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_413ebc17b7810865da85150c8c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48bdd63b173fe20acd39339515"`);
        await queryRunner.query(`DROP TABLE "planejamento_elementos_gamificacao_gamificacao"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49a910f747d3ed5adb2cb4a1d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a059397ee94b3ef1cfe211a57b"`);
        await queryRunner.query(`DROP TABLE "planejamento_recompensas_recompensa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ba1ca6373cf4a240461125a4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5265f6bcdf5b87ada1dec5b799"`);
        await queryRunner.query(`DROP TABLE "planejamento_regras_regra"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39cff654c9e94491744c778587"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_afdcd96d8818bd43fad8c4c06f"`);
        await queryRunner.query(`DROP TABLE "planejamento_scrums_scrum"`);
        await queryRunner.query(`DROP TABLE "sugestao"`);
        await queryRunner.query(`DROP TABLE "turma"`);
        await queryRunner.query(`DROP TABLE "planejamento"`);
        await queryRunner.query(`DROP TABLE "mapeamento"`);
        await queryRunner.query(`DROP TABLE "agrupamento_mapeamento"`);
        await queryRunner.query(`DROP TABLE "gamificacao"`);
        await queryRunner.query(`DROP TABLE "agrupamento_gamificacao"`);
        await queryRunner.query(`DROP TABLE "recompensa"`);
        await queryRunner.query(`DROP TABLE "agrupamento_recompensa"`);
        await queryRunner.query(`DROP TABLE "acao_recompensada"`);
        await queryRunner.query(`DROP TABLE "cenario_desejado"`);
        await queryRunner.query(`DROP TABLE "cenario_atual"`);
        await queryRunner.query(`DROP TABLE "perfil_jogador"`);
        await queryRunner.query(`DROP TABLE "regra"`);
        await queryRunner.query(`DROP TABLE "scrum"`);
        await queryRunner.query(`DROP TABLE "agrupamento_scrum"`);
    }

}
